name: Build
concurrency:
  group: build-eden-${{ github.ref }}-${{ github.event.inputs.job_to_run || 'all' }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      job_to_run:
        type: choice
        description: 'Choose target build platform'
        options:
          - all
          - windows
          - appimage
          - macos
          - android
          - freebsd
          - info
        default: 'all'

jobs:
  info:
    if: github.event.inputs.job_to_run == 'all' || github.event.inputs.job_to_run == 'info'
    runs-on: ubuntu-latest
    name: "Get info"
    strategy:
      matrix:
        target: [Info]
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          persist-credentials: false

      - name: Get the latest release count
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          api_url="https://api.github.com/repos/${{ github.repository }}"
          latest_release_info=$(curl -H "Authorization: token $GH_TOKEN" "$api_url/releases/latest")
          last_release_tag=$(echo "$latest_release_info" | jq -r '.tag_name')
          echo "${last_release_tag}"
          old_count="${last_release_tag##*-}"
          echo "OLD_COUNT=$old_count" >> "$GITHUB_ENV"

      - name: Generate changelog
        run: |
          chmod +x ./changelog.sh
          ./changelog.sh

      - name: Upload tag file
        uses: actions/upload-artifact@v4.6.2
        with:
          name: tag
          path: ~/tag

      - name: Upload count file
        uses: actions/upload-artifact@v4.6.2
        with:
          name: count
          path: ~/count

      - name: Upload changelog file
        uses: actions/upload-artifact@v4.6.2
        with:
          name: changelog
          path: ~/changelog

      - name: Upload source code
        uses: actions/upload-artifact@v4.6.2
        with:
          name: source
          path: artifacts

  appimage:
    if: github.event.inputs.job_to_run == 'all' || github.event.inputs.job_to_run == 'appimage'
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - target: steamdeck
            runs-on: ubuntu-latest
          - target: rog
            runs-on: ubuntu-latest
          - target: common
            runs-on: ubuntu-latest
          - target: legacy
            runs-on: ubuntu-latest
          - target: aarch64
            runs-on: ubuntu-24.04-arm
          - target: steamdeck-pgo
            runs-on: ubuntu-latest
          - target: rog-pgo
            runs-on: ubuntu-latest
          - target: common-pgo
            runs-on: ubuntu-latest
          - target: legacy-pgo
            runs-on: ubuntu-latest
          - target: aarch64-pgo
            runs-on: ubuntu-24.04-arm
    continue-on-error: true
    container: ghcr.io/pkgforge-dev/archlinux:latest
    name: "Appimage (${{ matrix.target }})"
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          chmod +x ./linux-dependencies.sh
          ./linux-dependencies.sh

      - name: Clone Eden
        run: |
          git clone 'https://git.eden-emu.dev/eden-emu/eden.git' ./eden

      - name: Restore cpm cache for ${{ matrix.target }}
        uses: actions/cache/restore@v4
        id: restore-cpm-cache
        with:
          path: |
            ${{ github.workspace }}/eden/.cache
          key: ${{ runner.os }}-cpm-${{ matrix.target }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-cpm-${{ matrix.target }}-

      - name: Compile Eden ${{ matrix.target }}
        run: |
          chmod +x ./eden-appimage.sh
          ./eden-appimage.sh ${{ matrix.target }}

      - name: Upload appimage
        uses: actions/upload-artifact@v4.6.2
        with:
          name: eden-${{ matrix.target}}-appimage
          path: eden/appimage

      - name: Upload appbundle
        uses: actions/upload-artifact@v4.6.2
        with:
          name: eden-${{ matrix.target}}-appbundle
          path: eden/appbundle

      - name: Save cpm cache for ${{ matrix.target }}
        if: ${{ github.ref_name == 'main' }}
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ github.workspace }}/eden/.cache
          key: ${{ steps.restore-cpm-cache.outputs.cache-primary-key }}

  android:
    if: github.event.inputs.job_to_run == 'all' || github.event.inputs.job_to_run == 'android'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [Replace, Coexist, Optimised]
    continue-on-error: true
    name: "Android (${{ matrix.target }})"
    env:
      TARGET: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install sccache glslang-tools libvulkan-dev python3-requests -y

      - name: Clone Eden
        run: |
          git clone 'https://git.eden-emu.dev/eden-emu/eden.git' ./eden

      - name: Restore cpm cache for ${{ matrix.target }}
        uses: actions/cache/restore@v4
        id: restore-cpm-cache
        with:
          path: |
            ${{ github.workspace }}/eden/.cache
          key: ${{ runner.os }}-android-cpm-${{ matrix.target }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-android-cpm-${{ matrix.target }}-

      - name: Restore sccache for ${{ matrix.target }}
        uses: actions/cache/restore@v4
        id: restore-sccache-cache
        with:
          path: ~/.cache/sccache/
          key: ${{ runner.os }}-android-sccache-${{ matrix.target }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-android-sccache-${{ matrix.target }}-

      - name: Compile Eden android
        run: |
          chmod +x ./eden-android.sh
          ./eden-android.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: eden-android-${{ matrix.target }}
          path: eden/src/android/artifacts/

      - name: Save cpm cache for ${{ matrix.target }}
        if: ${{ github.ref_name == 'main' }}
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ github.workspace }}/eden/.cache
          key: ${{ steps.restore-cpm-cache.outputs.cache-primary-key }}

      - name: Save sccache for ${{ matrix.target }}
        if: ${{ github.ref_name == 'main' }}
        uses: actions/cache/save@v4
        with:
          path: ~/.cache/sccache/
          key: ${{ steps.restore-sccache-cache.outputs.cache-primary-key }}

  windows:
    if: github.event.inputs.job_to_run == 'all' || github.event.inputs.job_to_run == 'windows'
    runs-on: ${{ matrix.runs-on }}
    name: "Windows ${{ matrix.target }} ${{ matrix.toolchain }} (${{ matrix.arch }})"
    continue-on-error: true
    strategy:
      matrix:
        include:
           - toolchain: msvc
             target: normal
             arch: x86_64
             runs-on: windows-2022
           - toolchain: msvc
             target: normal
             arch: arm64
             runs-on: windows-11-arm
           - toolchain: clang
             target: normal
             arch: x86_64
             runs-on: windows-2022
           - toolchain: clang
             target: normal
             arch: arm64
             runs-on: windows-11-arm
           - toolchain: clang
             target: PGO
             arch: x86_64
             runs-on: windows-2022
           - toolchain: clang
             target: PGO
             arch: arm64
             runs-on: windows-11-arm
    env:
      TOOLCHAIN: ${{ matrix.toolchain }}
      ARCH: ${{ matrix.arch }}
      TARGET: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v4.3.0
        with:
          version: '6.9.1'

      - name: Install vulkan-sdk
        shell: powershell
        run: |
          ./install-vulkan-sdk.ps1

      - name: Force Clang 20
        if: matrix.toolchain == 'clang'
        shell: bash
        run: |
          echo "C:/Program Files/LLVM/bin" >> $GITHUB_PATH
          
      - name: Clone Eden
        shell: bash
        run: |
          git clone 'https://git.eden-emu.dev/eden-emu/eden.git' ./eden
          cd ./eden
          echo "VERSION=$(git rev-list --count HEAD)" >> "${GITHUB_ENV}"

      - name: Restore cpm cache
        uses: actions/cache/restore@v4
        id: restore-cpm-cache
        with:
          path: |
            ${{ github.workspace }}/eden/.cache
          key: ${{ runner.os }}-cpm-${{ matrix.target }}-${{ matrix.toolchain }}-${{ matrix.arch }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-cpm-${{ matrix.target }}-${{ matrix.toolchain }}-${{ matrix.arch }}-

      - name: Compile Eden Windows
        shell: bash
        run: |
          chmod +x ./eden-windows.sh
          ./eden-windows.sh

      - name: Generate installer
        shell: cmd
        working-directory: ${{ github.workspace }}/installer
        run: |
          set TOOLCHAIN=%TOOLCHAIN%
          if /I "%TARGET%"=="PGO" set TOOLCHAIN=PGO-%TOOLCHAIN%
          makensis /DPRODUCT_TOOLCHAIN=%TOOLCHAIN% /DPRODUCT_VARIANT=%ARCH% /DPRODUCT_VERSION=%VERSION% eden.nsi
          mkdir artifacts 2>nul
          move /y *.exe artifacts\

      - name: Upload Eden 7z
        uses: actions/upload-artifact@v4.6.2
        with:
          name: eden-windows-${{ matrix.toolchain }}-${{ matrix.target }}-7z-${{ matrix.arch }}
          path: eden/build/artifacts/

      - name: Upload Eden installer
        uses: actions/upload-artifact@v4.6.2
        with:
          name: eden-windows-${{ matrix.toolchain }}-${{ matrix.target }}-installer-${{ matrix.arch }}
          path: installer/artifacts/

      - name: Save cpm cache
        if: ${{ github.ref_name == 'main' }}
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ github.workspace }}/eden/.cache
          key: ${{ steps.restore-cpm-cache.outputs.cache-primary-key }}

  macos:
    if: github.event.inputs.job_to_run == 'all' || github.event.inputs.job_to_run == 'macos'
    runs-on: ${{ matrix.runs-on }}
    name: "MacOS (${{ matrix.target }})"
    strategy:
      matrix:
        include:
          - target: x86_64
            runs-on: macos-13
          - target: arm64
            runs-on: macos-latest
    continue-on-error: true
    env:
      TARGET: ${{ matrix.target }}
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: content
      CCACHE_SLOPPINESS: time_macros
    steps:
      - uses: actions/checkout@v5

      - name: Clone Eden
        run: |
          git clone 'https://git.eden-emu.dev/eden-emu/eden.git' ./eden

      - name: Restore cpm cache for ${{ matrix.target }}
        uses: actions/cache/restore@v4
        id: restore-cpm-cache
        with:
          path: |
            ${{ github.workspace }}/eden/.cache
          key: ${{ runner.os }}-cpm-${{ matrix.target }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-cpm-${{ matrix.target }}-

      - name: Restore ccache for ${{ matrix.target }}
        uses: actions/cache/restore@v4
        id: restore-ccache-cache
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-${{ matrix.target }}-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-ccache-

      - name: Install dependencies
        run: |
          brew install --formula --quiet autoconf automake boost ccache glslang hidapi libiconv libtool nasm speexdsp vulkan-loader vulkan-headers vulkan-utility-libraries molten-vk

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.7.3
          cache: 'true'

      - name: Compile Eden MacOS (${{ matrix.target }})
        run: |
          chmod +x ./eden-macos.sh
          ./eden-macos.sh

      - name: Upload
        uses: actions/upload-artifact@v4.6.2
        with:
          name: eden-macos-${{ matrix.target }}
          path: eden/build/artifacts/

      - name: Save cpm cache for ${{ matrix.target }}
        if: ${{ github.ref_name == 'main' }}
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ github.workspace }}/eden/.cache
          key: ${{ steps.restore-cpm-cache.outputs.cache-primary-key }}

      - name: Save ccache for ${{ matrix.target }}
        if: ${{ github.ref_name == 'main' }}
        uses: actions/cache/save@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ steps.restore-ccache-cache.outputs.cache-primary-key }}

  freebsd:
    if: github.event.inputs.job_to_run == 'all' || github.event.inputs.job_to_run == 'freebsd'
    name: FreeBSD
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [FreeBSD, FreeBSD-PGO]
    continue-on-error: true
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      TARGET: ${{ matrix.target }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0
        
      - name: Clone Eden
        run: |
          git clone 'https://git.eden-emu.dev/eden-emu/eden.git' ./eden

      - name: Restore cpm cache
        uses: actions/cache/restore@v4
        id: restore-cpm-cache
        with:
          path: |
            ${{ github.workspace }}/eden/.cache
          key: ${{ matrix.target }}-cpm-${{ github.sha }}
          restore-keys: ${{ matrix.target }}-cpm-

      - name: Compile Eden FreeBSD
        uses: vmactions/freebsd-vm@v1.2.4
        with:
          usesh: true
          envs: 'CCACHE_DIR TARGET'
          run: |
            chmod +x ./freeBSD-dependencies.sh ./eden-freeBSD.sh
            ./freeBSD-dependencies.sh
            ./eden-freeBSD.sh

      - name: Upload
        uses: actions/upload-artifact@v4.6.2
        with:
          name: eden-${{ matrix.target }}
          path: eden/build/artifacts/

      - name: Save cpm cache
        if: ${{ github.ref_name == 'main' }}
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ github.workspace }}/eden/.cache
          key: ${{ steps.restore-cpm-cache.outputs.cache-primary-key }}

  release:
    if: github.ref_name == 'main' && github.event.inputs.job_to_run == 'all'
    name: "release"
    needs: [info, appimage, windows, macos, android, freebsd]
    permissions:
      actions: read
      security-events: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5.0.0
        with:
          pattern: "*"
          merge-multiple: true

      - name: Generate changelog
        run: |
          echo "TAG=$(cat tag)" >> "${GITHUB_ENV}"
          echo "COUNT=$(cat count)" >> "${GITHUB_ENV}"
          echo "BODY<<EOF" >> "${GITHUB_ENV}"
          cat changelog >> "${GITHUB_ENV}"
          echo "EOF" >> "${GITHUB_ENV}"

      - name: Release Eden
        uses: softprops/action-gh-release@v2.3.3
        with:
          name: "Eden Unofficial Nightly Release: ${{ env.COUNT }}"
          tag_name: "${{ env.TAG }}"
          body: "${{ env.BODY }}"
          prerelease: false
          draft: false
          generate_release_notes: false
          fail_on_unmatched_files: false
          make_latest: true
          files: |
            *.AppImage*, *.AppBundle*, *.7z, *.tar.xz, *.exe, *.apk
